//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityLayer
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class comment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public comment()
        {
            this.step_comment = new HashSet<step_comment>();
        }
    
        public int cid { get; set; }
        [Display(Name = "Comment")]
        public string text { get; set; }
        [Display(Name = "TimeStamp")]
        public System.DateTime timestamp { get; set; }
        [Display(Name = "User")]
        public string uid { get; set; }
        [Display(Name = "File Name")]
        public string fpath { get; set; }
        [Display(Name = "File Comment")]
        public Nullable<bool> isfile { get; set; }
    
        public virtual user user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<step_comment> step_comment { get; set; }
    }
}
