//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityLayer
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public project()
        {
            this.accesses = new HashSet<access>();
            this.project_step = new HashSet<project_step>();
        }
    
        public int pid { get; set; }
        [Display(Name = "Project Name")]
        public string name { get; set; }
        [Display(Name = "Creator's Name")]
        public string creator_name { get; set; }
        [Display(Name = "Creator's Email")]
        public string creator_email { get; set; }
        [Display(Name = "Creation Time")]
        public System.DateTime creation_time { get; set; }
        [Display(Name = "Estimated Date of Completion Original")]
        public System.DateTime est_doc_ori { get; set; }
        [Display(Name = "Estimated Date of Completion Current")]
        public Nullable<System.DateTime> est_doc_cur { get; set; }
        [Display(Name = "Actual Date of Completion")]
        public Nullable<System.DateTime> actual_doc { get; set; }
        [Display(Name = "Progress")]
        public Nullable<int> progress { get; set; }
        [Display(Name = "Status")]
        public string status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<access> accesses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<project_step> project_step { get; set; }
    }
}
