//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class step_comment
    {
        public int sid { get; set; }
        public int cid { get; set; }
        public int Id { get; set; }
    
        public virtual comment comment { get; set; }
        public virtual step step { get; set; }
    }
}
