//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityLayer
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class step
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public step()
        {
            this.project_step = new HashSet<project_step>();
            this.step_comment = new HashSet<step_comment>();
            this.step_justification = new HashSet<step_justification>();
        }
    
        public int sid { get; set; }
        [Display(Name = "Status")]
        public string step_status { get; set; }
        [Display(Name = "Step")]
        public string name { get; set; }
        public string description { get; set; }
        [Display(Name = "Estimated Start Date")]
        public System.DateTime est_start_date { get; set; }
        [Display(Name = "Estimated End Date")]
        public System.DateTime est_end_date { get; set; }
        [Display(Name = "Actual Start Date")]
        public Nullable<System.DateTime> actual_start_date { get; set; }
        [Display(Name = "Actual End Date")]
        public Nullable<System.DateTime> actual_end_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<project_step> project_step { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<step_comment> step_comment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<step_justification> step_justification { get; set; }
    }
}
