//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public project()
        {
            this.accesses = new HashSet<access>();
            this.project_steps = new HashSet<project_steps>();
        }
    
        public int pid { get; set; }
        public string name { get; set; }
        public string creator_name { get; set; }
        public System.DateTime creation_time { get; set; }
        public System.DateTime est_doc_ori { get; set; }
        public Nullable<System.DateTime> est_doc_cur { get; set; }
        public Nullable<System.DateTime> actual_doc { get; set; }
        public Nullable<int> progress { get; set; }
        public string status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<access> accesses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<project_steps> project_steps { get; set; }
    }
}
